packages:
  # All CLIs (both Python and Node) are under cli/ folders
  # pnpm will only pick up folders with package.json
  - "common/cli/*"
  - "nab/cli/*"
  - "tinybots/cli/*"
  # Legacy tinybots local package
  - "tinybots/local"
